INSERT INTO products (url, url_two, url_three, title, company, review_number, review_one, review_two, review_three, review_titleone, review_titletwo, review_titlethree,amazon_choice,  prime, price, review_personone, review_persontwo, review_personthree) VALUES
(
  'https://images-na.ssl-images-amazon.com/images/I/41iz5Tw82IL._SY300_QL70_.jpg',
  'https://images.unsplash.com/photo-1522780550166-284a0288c8df?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ad81d7fc6027a637ddbb3804d700403e&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b5625f6fd6feaf34cc3e2a3e28dbf40&auto=format&fit=crop&w=967&q=80',
  'Echo Dot',
  'Amazon',
  '120,393',
  'Having worked in the electronics retail industry for years now, I have seen scores of Smart devices come and go. Until now, nobody quite got it right. In the Echo Dot, Amazon has created a near perfect blend of hardware and software.',
  'You need an iphone (and only an iphone) to setup drop-in for an echo dot and an echo on the same wifi. Why? A $700 device to connect two sub-$100 devices to each other through an app that already recognizes, that is ridiculous.',
  'Whether you just want the weather, latest sports scores or help with a math problem, Alexa will help. We now have 3 in the house and will be adding two more. With a simple $3 subscription to Amazons music service, you can stream almost any music you can think of by simply asking Alexa for it!',
  'A Must buy',
  'Great holiday gift!',
  'Love the Echo',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$19.99',
  'By John Smith, Chicago on 20-Nov-2018',
  'By Caroline Crozier, Nashville on 31-Oct-2018',
  'By Jamal Harris, New York 15-Aug-2018'
),
(
  'https://n.nordstrommedia.com/id/5f61e17a-f79c-498e-983c-583a94d451da.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/152d33ed-ea1f-4c16-89ca-95f9562886c6.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/32e7658c-9168-4e8b-816d-8d4fb4b1bc14.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838',
  'Alminette Pointy Toe Pump',
  'CHRISTIAN LOUBOUTIN',
  '196',
  'Having worked in the electronics retail industry for years now, I have seen scores of Smart devices come and go. Until now, nobody quite got it right. In the Echo Dot, Amazon has created a near perfect blend of hardware and software.',
  'You need an iphone (and only an iphone) to setup drop-in for an echo dot and an echo on the same wifi. Why? A $700 device to connect two sub-$100 devices to each other through an app that already recognizes, that is ridiculous.',
  'Whether you just want the weather, latest sports scores or help with a math problem, Alexa will help. We now have 3 in the house and will be adding two more. With a simple $3 subscription to Amazons music service, you can stream almost any music you can think of by simply asking Alexa for it!',
  'Perfect shoes',
  'How to make a statement 101',
  'Amazing',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$675.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  );
