INSERT INTO products (url, url_two, url_three, title, company, review_number, review_one, review_two, review_three, review_titleone, review_titletwo, review_titlethree, amazon_choice,  prime, price, review_personone, review_persontwo, review_personthree) VALUES
(
  'https://images-na.ssl-images-amazon.com/images/I/41iz5Tw82IL._SY300_QL70_.jpg',
  'https://images.unsplash.com/photo-1522780550166-284a0288c8df?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ad81d7fc6027a637ddbb3804d700403e&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b5625f6fd6feaf34cc3e2a3e28dbf40&auto=format&fit=crop&w=967&q=80',
  'Echo Dot',
  'Amazon',
  '120,393',
  'Having worked in the electronics retail industry for years now, I have seen scores of Smart devices come and go. Until now, nobody quite got it right. In the Echo Dot, Amazon has created a near perfect blend of hardware and software.',
  'You need an iphone (and only an iphone) to setup drop-in for an echo dot and an echo on the same wifi. Why? A $700 device to connect two sub-$100 devices to each other through an app that already recognizes, that is ridiculous.',
  'Whether you just want the weather, latest sports scores or help with a math problem, Alexa will help. We now have 3 in the house and will be adding two more. With a simple $3 subscription to Amazons music service, you can stream almost any music you can think of by simply asking Alexa for it!',
  'A Must buy',
  'Great holiday gift!',
  'Love the Echo',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$19.99',
  'By John Smith, Chicago on 20-Nov-2018',
  'By Caroline Crozier, Nashville on 31-Oct-2018',
  'By Jamal Harris, New York 15-Aug-2018'
),
(
  'https://n.nordstrommedia.com/id/5f61e17a-f79c-498e-983c-583a94d451da.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/152d33ed-ea1f-4c16-89ca-95f9562886c6.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/32e7658c-9168-4e8b-816d-8d4fb4b1bc14.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838',
  'Alminette Pointy Toe Pump',
  'Christian LouBoutin',
  '196',
  'I love strutting in my red stilettos down the streets in Norway. It really makes a statement in -5 celsius. Even when I am out late hitting the town, these shoes always get me home',
  'These shoes are sickkkkkk. When I am on chat roulette, I love to show my heels off to my new friends.',
  'LouBoutin is the perfect blend of classy, yet alluring. When I am playing a challenging game of chess, these shoes give me the confidence to think three steps ahead. #checkmate' ,
  'Perfect shoes',
  'How to make a statement 101',
  'Amazing',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$675.00',
  'By Kozak, Svalbard on 20-Nov-2018',
  'By Ross Ludeke, Dubai on 31-Oct-2018',
  'By Sam Pryor, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/1e6d4066-a2fa-4951-83ab-fc0e7cef5480.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/4c111e27-9b71-45ee-ab63-9a14f68f5b65.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/602ab95c-7eae-4e52-bbf1-a38f42d2acc4.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'Small Robinson Leather Tote',
  'Tori Burch',
  '26',
  'Beautiful purse! This purse arrived and it was more beautiful than expected! I like a medium sized purse and this is perfect! Also, I like the zip closure so nothing falls out. Very classy looking!',
  'Cute, lovely purse. The red color is gorgeous, adds a nice pop of color with any outfit. Has a lot of pockets, able to fit my cell phone and very large wallet easily. Leather seems to be very good quality.',
  'Purchased same Tote in Pale Apricot for Spring/Summer and was so pleased that I purchased in Black for Fall/Winter. Pockets, zipper & dual compartments keep items separated & easy to locate. Attractive & perfect size. Definitely a good investment!',
  'Cute, practical bag',
  'Great Functional Bag',
  'Tory Burch Handbag',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$298.00',
  'By Arleen Santana, Tokoyo on 21-Nov-2018',
  'By Amanda Gorfine, Paris on 31-Oct-2018',
  'By Sam Pryor, Rome 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/30385a0c-93ac-47e1-8495-ecd5ad327084.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/f5281269-1273-46a7-be42-d432611374ad.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/0155c29f-289b-4844-a7a9-5583221f4778.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'Wool Runner',
  'AllBirds',
  '7',
  'These are my first pair of AllBirds after being recommended this shoe by several people. I get the hype- they are extremely comfortable and a great looking shoe that I can wear all day and even to work. I hear their washable too so I will have to try that once I have had them a little longer.',
  'These are my first pair of Allbirds. They are comfortable and better than I anticipated. The wool is soft not scratchy and you really can wear them all day and forget they are in your feet. I have worn them both with and without socks. I can’t say enough good things about these shoes.',
  'These are warm, durable and so comfortable. Cant wait to get more for all of my family.',
  'Great all around shoe',
  'Super comfy!',
  'Comfy AllBirds',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$98.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/1ff3ae8a-ee53-4cd3-8d0a-4832ea91892a.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/ab9e99a4-a702-4ff8-a303-4d5e860e30fa.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/ab9e99a4-a702-4ff8-a303-4d5e860e30fa.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Nourishing Dream Team',
  'Kiehls',
  '196',
  'quite good product, I always like Kiehls product',
  'Such a great gift for my mother. She loved it!',
  'Made my face feel hydrated after a long, cold winter',
  'Good product',
  'Great gift for the holidays',
  'Your face will thank you',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$18.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/35622787-bbbc-4a16-935e-4b32b5afc149.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/650360c1-df74-4323-8dc8-5940baa7588e.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/650360c1-df74-4323-8dc8-5940baa7588e.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Water Repellent 600-Fill Power Down Sweater Jacket',
  'Patagonia',
  '5',
  'True to Patagonia, here is a puffy jacket that is truly a quality jacket and one which kids will want to wear. The red color is not a bright red but is a nice slightly darker shade of red, plus the black trim looks great. The 2T fit true to size.',
  'Love Patagonia jackets for toddlers. They hold up very well for a kid who is constantly climbing at the playground. We always order a size up and they last the entire season.',
  'Highly recommend this jacket. Go a size up it does run a little small. Perfect for cold weather',
  'Sweet Jacket!',
  'Great jacket for active kid!',
  'Highly recommend',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$99.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/20c0f25a-92f5-4ba4-b3b2-7d5212aa50b6.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/a3fe77a1-950a-4654-80ac-1347d860ca3e.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/10671f0a-2a1c-4fd9-95de-7da909fa3d45.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Kennebunk Bliss Plush Throw',
  'Nordstrom',
  '2,450',
  'This blanket is so soft and such a great gift! It is a very nice quality for the price!',
  'Love these blankets. Always buy them for gifts because who doesnt love a soft cozy blanket. Its a good size and looks great on a sofa.',
  'Needed to get a nice throw for my bed. My dog adopted my last pricy one, which ended up needing to get washed way too often and loose is softness and fluff...So this $40 baby will have to be the new bed throw. It’s so soft and cozy and until it becomes my dog’s, it will do!',
  'Great soft blanket!',
  'Great gift for you or your friends',
  'My dog will probably hog it',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$29.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/e2b1622a-fe22-4ebf-ba98-83088a070480.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/85c1bd68-8fa2-4152-8070-9ce88c88c116.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/58b4837e-f1f1-4cbb-9e75-ced5b857daae.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Sophia Drop Earrings',
  'Kendra Scott',
  '458',
  'Love these earrings and they are just what I was looking for!',
  'I bought the earrings for my daughters birthday to match the necklace her boyfriend bought her last year. She was super excited.',
  'Love these, perfect with any outfit!',
  'Beautiful earrings!',
  'Birthday Present',
  'Perfect Earrings',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$50.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/a563f7f4-baf6-4410-907b-488b2c36a519.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/a4a52422-9202-4363-88ed-b4e8c2f750c0.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/990778b8-5785-4b4e-afe0-e3d725ee088e.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Circle of Life Pendant Necklace',
  'Anna Beck',
  '230',
  'Great versatile piece. Love the two tone and ability to reverse sides for new looks',
  'This necklace is simple but far from ordinary - the craftsmanship is exceptional and the details of the Gili pattern are iconic. Anna Beck pieces are timeless and well made, and she supports womens health care in Lombok with her profits, so you can feel even better wearing this! My daughter and I are big fans!',
  'This necklace is a perfect everyday piece. I get so many compliments when I wear it. It’s not heavy on your neck and the clasp is secure and easy to put on. High quality which is typical of all Anna Beck jewelry. Love her pieces and love that she gives back too!',
  'Classic',
  'Great Versatile Piece',
  'Love Anna Beck jewelry',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$175.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/2306d211-752d-491d-bb10-1efa6583f114.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/3254a912-16d7-4c10-97a8-c601a252202b.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/2306d211-752d-491d-bb10-1efa6583f114.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  '50s Retro Style Toaster',
  'Smeg',
  '50',
  'I love this toaster it’s look fabulous on the counter',
  'Stunning look and delicious toast every time! I’ve been looking for the perfect toaster for ten years and have finally found it! Thrilled about my smeg and so is my family! Defroster button?! Sandwich baskets you can buy separately?! Bagel button?! Amazing.',
  'Pretty, sleek, retro design (got it in black). Long toast slots which are great for an array of slice sizes, keep warm setting which is pretty neat. Plus I love the background of the company itself!',
  'I love this toaster',
  'Works like a Dream',
  'Great toaster!',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$199.95',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/e028d4cc-5dfc-448d-b423-d3517bf4d114.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
   'https://n.nordstrommedia.com/id/0b702e16-0c01-4029-b945-5da3e35e1779.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
   'https://n.nordstrommedia.com/id/e9b537d0-90c9-479d-9b6d-8cc9a9422472.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'Little America - Mid Volume Backpack',
  'Herschel Supply Co.',
  '49',
  'Stylish bag for my 8th grader. She loves it and especially the computer pocket. Well constructed.',
  'This is the second Herschel backpack I’ve had. The quality of these backpacks is amazing. They are easy to clean and never tear. This backpack has a padded area for my laptop and it’s very well protected. Only thing missing is an outer pocket for a water bottle.',
  'Absolutely love this backpack! The jade green is a beautiful hue, the inside is spacious, and I love the padded pocket for laptop. The snaps are magnetic for easy closure. Highly recommend this bag!',
  'Stylish 8th grader',
  'Herschel backpack',
  'Herschel backpack',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$100.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/2811af19-01ca-418b-9112-aa5e7701cd22.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/2a820314-61f8-4209-877e-788f4dfc7e43.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/64262c81-2fe4-44c9-af55-2f122d5f11c7.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'Mesa Chelsea Boot',
  'The Rail',
  '27',
  'this boot looks great. will be purchasing more colors',
  'This is the second Herschel backpack I’ve had. The quality of these backpacks is amazing. They are easy to clean and never tear. This backpack has a padded area for my laptop and it’s very well protected. Only thing missing is an outer pocket for a water bottle',
  'These shoes are very nice quality and color is similar to the photo. I would expect to use a water repellant in them. They came in and were quite larger than expected and I needed to size down. However, the size desired was no longer available. Will be returning',
  'Perfect shoes',
  'Nice but odd sizing',
  'Good boot but not true to size',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$59.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/b16ba540-086a-419f-8abc-5ac0b4ff6ade.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/0459e5a2-ac77-435c-8361-d97c3d033853.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/0459e5a2-ac77-435c-8361-d97c3d033853.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'SoundLink® Micro Bluetooth® Speaker',
  'Bose',
  '214',
  'LOVE this speaker! I own 2. These speaker are small & so convenient. These speakers are loud & great quality sound! I was surprised how big of a sound could come from such a small speaker. I use 1 of these every day at my desk tonlisten to music. I have also used them for business events & parties.',
  'As all things Bose this speaker is excellent. The sound is crystal clear. Well worth the price specially with the $40 discount.',
  'This speaker is impressive! I bought it for my fiance to take to the beach or kayaking. We tested it in the house and can hear it from every single room! It definitely packs a punch! We look forward to using it on many adventures!',
  'Awesome, convenient speaker!',
  'Sounds great!',
  'Packs a Punch!',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$79.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/a6911d17-f563-4bb3-b132-5fea861f6056.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/551aaea8-d9af-49db-93cd-df0f2ab43ba4.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/33dd2cc3-5e12-4395-a94b-9be90296b37f.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Half Mega Fashion Wool Fringe Scarf',
  'Burberry',
  '7',
  'This scarf is so soft! It says “half” but is a great length. AWESOME Burberry purchase for a great price.',
  'These oversize burberry scarves are simply the best. I have the camel and the blue, and Im obsessed. I kind of want all the colors. I have other more expensive burberry scarves, and these are better. Love!',
  'I watched scarf for months. Finally decided to purchase it and Im super happy I did. I love it and have gotten so many compliments on it. Great investment piece.',
  'Best burberry scarves!',
  'Unique Scarf',
  'Foxxymom03',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  'Sold Out',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/68d58559-67cb-47a8-b71a-acc98a7d93cf.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/c64c39ca-27b3-471f-8b6f-d5f7ca6541b2.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'https://n.nordstrommedia.com/id/faa7d9d1-b4b7-4977-b5a1-5776531c603d.jpeg?crop=pad&pad_color=FFF&format=jpeg&trim=color&trimcolor=FFF&w=780&h=838&quality=70',
  'Original Rain Boot',
  'Hunter',
  '168',
  'My daughter is 8 and this is her 5th pair over the years I’ve purchased for her. She wears them with everything!!! Very comfortable since she goes for them day after day for school.',
  'My daughters have worn Hunter boots since age 2. They are now age 9 & 5. Quality is excellent and withstands the variety of climate changes in Toronto. I love the colour choices!',
  'I bought this last month and it’s kinda big but it’s okay it’s still comfy.',
  'Cute even in any weather',
  'Would purchase again!',
  'Comfy',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$80.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/99cfbd74-f9d1-450a-a60f-5c745c73d173.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/59b00cf3-72b2-48cc-85ae-177a8e918df7.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/0fa5f5b5-188a-4774-bef5-f5a093a25f38.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Cruiser Deluxe Turntable',
  'Crosley Radio',
  '15',
  'Perfect nostalgic gift! Was able to find a record to along as the gift and was definitely a hit! I love how it has the option to pay music via bluetooth.',
  'I ordered mine last week. At first, I didnt expect anything from it. But, it turns out pretty well. The output of music and design of the turntable is superb. Also, I want to give Nordstrom customer service a thumbs up for an excellent job for helping me out on my order. I am so happy!',
  'Got this for my dad for Father’s Day and he loved it! His old record player needed external speakers so having speakers built in was ideal for me. Plus, the size is great and doesn’t take up much space.',
  'Awesome Gift!',
  'My type of turntable',
  'Great gift for dad!',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$69.95',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/82389ec0-b1d6-4bfd-96f4-e936aacf308a.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/f44b28fc-4f42-4c20-afc0-e4e12165ca79.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/bb8e84e1-38a7-4d5d-bf97-0c5a5ed6b010.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196',
  'Wood Sage & Sea Salt Cologne',
  'Jo Malone London',
  '297',
  'Surprised out how much I love this one-I enjoy floral perfumes and expected to hate this one. Not at all floral yet not masculine. Fresh & does NOT smell like anything else that Ive tried.',
  'Such a fan of this scent. Its hard to describe but its not too sweet and not too strong and gets better the longer its on the skin, which isnt always the case with fragrance.',
  'I have been on the hunt for the perfect perfume and I have now found it! Every scent I would try was too flowery or just didn’t fit my personality but this wood sage and sea salt it so perfect. When I smell it it makes me happy and reminds me of summer. I will be wearing this for a very long time!!!',
  'Refreshing & Unique',
  'Its not your sisters flower/candy fragrance.',
  'Absolute favorite',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$68.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/454224b7-72cf-4844-a7a2-af66ecea199b.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/29365b5e-186e-43ca-ae55-d7d9ef548036.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/9fbb9518-d7ac-453b-9c46-0e05d1282005.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Wood Kitchen',
  'Janod',
  '196',
  'This is the most adorable little kitchenette! Absolutely perfect size for my 15 month old daughter. She plays with it daily and loves opening and shutting the doors!! Highly recommende! Great size for condo living!!',
  'So cute and a great size to tuck away when it is not being used',
  'My son loves Top Chef so we bought this for him, and he loves to play with it and pretend he is on the show',
  'Baby girl kitchenette',
  'Great gift',
  'My son loves this playset!',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$95.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/77142df5-1c6c-4ae8-8ac7-b83e1422c50c.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/05f05d06-8ba4-4ede-888d-77477e158adb.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/ac2503f1-22cc-4293-9d87-f3a4312c597e.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Carson Slim Fit Hooded Packable ',
  'Canada Goose',
  '17',
  'The fit is perfect. warm, looks very stylish on. 5’10 165 lbs Medium',
  'Yes, its pricey but worth it. The pockets are a little too shallow for my liking but, overall, it is an awesome coat. I did not expect so many compliments on it either.',
  'Really nice fit. Looks really good.',
  'Hellll yeah',
  'Really love it.',
  'Canada goose',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$995.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  ),
(
  'https://n.nordstrommedia.com/id/0c8d090e-3a47-471b-9f05-f805f7cb0f59.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/bad62bfb-f95e-44b5-8efc-bab79d55d1ec.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'https://n.nordstrommedia.com/id/24002203-8415-403b-9e08-2ac748e5d335.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&quality=70',
  'Recipe Cocktail Shaker',
  'Nordstrom',
  '19',
  'I gave this as a gift to my girlfriend and she uses it all the time to make us lovely cocktails in the evening.',
  'So much fun to use while hosting parties. Looks so stylish. ',
  'Really nice fit. Looks really good.',
  'Great for hosting',
  'Any cocktail lovers dream',
  'Love the Gold',
  'https://netrush.com/wp-content/uploads/2018/05/Amazons-Choice.jpg',
  'https://pngimage.net/wp-content/uploads/2018/06/prime-png-1.png',
  '$39.00',
  'By Ana Ravera, London on 20-Nov-2018',
  'By Murielle Salomon, Dubai on 31-Oct-2018',
  'By Sarah Currey, Paris 15-Aug-2018'
  );
